inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/schema.rb
  SuggestExtensions: false

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Rails/SaveBang:
  Exclude:
    - app/services/omniauth_sign_in_service.rb
